---
title: "Evidentiality as part of the tense system"
---
```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, message = FALSE)

# packages

library(tidyverse)
library(lingtypology)
library(DT)
library(RefManageR)


bib <- ReadBib(file = "bibliography.bib")
BibOptions(style = "html", bib.style = "authoryear", cite.style = "authoryear", max.names = 2)

# load data

vill <- read_tsv("data/villages.csv") # villages dataset
meta <- read_tsv("data/meta.csv") # language metadata and colors
ev <- read_tsv("data/evidentiality_tense.csv") # feature dataset

# preparation of data

vill <- vill[complete.cases(vill$lat),] # remove villages for which we do not have coordinates (yet)

meta_core <- meta %>% # remove idioms not (yet) recognized as distinct
  filter(core == "yes")

vill_meta <- merge(vill, meta_core, by = "lang") # merge villages and coordinates with language metadata

ev_vill <- merge(vill_meta, ev, by = "lang") # merge villages, coordinates, and language metadata with feature information

ev_vill$datapoint <- "extrapolated datapoint"

```
## Maps{.tabset .tabset-fade .tabset-pills}

### Map: Extrapolated data

```{r, echo=FALSE, warning=FALSE, message=FALSE, fig.width = 9.5}

# draw a map

map.feature(lang.gltc(ev_vill$glottocode),
            latitude = ev_vill$lat,
            longitude = ev_vill$lon,
            features = ev_vill$lang, # color feature = language
            color = ev_vill$lang_color_dagatlas,
            stroke.features = ev_vill$value, # stroke.feature = your feature value
            stroke.color = c("black", "white"), 
            label = ev_vill$lang,
            zoom.control = T,
            popup = paste("<b>Village:</b>", ev_vill$village, "<br>", 
                          "<b>Source:</b>", ev_vill$source, ev_vill$page, "<br>",
                          "<b>Datapoint:</b>", ev_vill$datapoint),
            width = 3, stroke.radius = 8,
            legend = FALSE)

```

### Map: General datapoints

```{r, echo=FALSE, warning=FALSE, message=FALSE, fig.width = 9.5}

# filter core languages

core_meta <- meta %>%
  filter(core == "yes")

core_data <- left_join(core_meta, ev, by = "lang")

core_data$datapoint <- "general datapoint"

# draw a map

map.feature(lang.gltc(core_data$glottocode),
            latitude = core_data$gltc_lat,
            longitude = core_data$gltc_lon,
            features = core_data$lang, # color feature = language
            color = core_data$lang_color_dagatlas,
            stroke.features = core_data$value, # stroke.feature = your feature value
            stroke.color = c("black", "white"), 
            label = core_data$lang,
            zoom.control = T,
            popup = paste("<b>Source:</b>", core_data$source, core_data$page, "<br>",
                          "<b>Datapoint:</b>", core_data$datapoint),
            width = 3, stroke.radius = 8,
            legend = FALSE)

```

### Map: Extrapolation and refinement

```{r, echo=FALSE, warning=FALSE, message=FALSE, fig.width = 9.5}

# create separate dataset for selected idiom: it is better to do this not in R and keep a separate table with the same structure as the features table, but with more detailed observations

zaqatala <- ev_vill %>%
  filter(idiom.x == "Zaqatala")

# remove this idiom from the general dataset

ev_vill_wozaqatala <- ev_vill %>%
  filter(!idiom.x %in% "Zaqatala")

# change the datapoint value for the subset

zaqatala$datapoint <- "idiom"

zaqatala$source <- "add"

# merge the general dataset with the updated information on the idiom

ev_vill_wzaqatala <- rbind(ev_vill_wozaqatala, zaqatala)

# draw a map

map.feature(lang.gltc(ev_vill_wzaqatala$glottocode),
            latitude = ev_vill_wzaqatala$lat,
            longitude = ev_vill_wzaqatala$lon,
            features = ev_vill_wzaqatala$lang, # color feature = language
            color = ev_vill_wzaqatala$lang_color_dagatlas,
            stroke.features = ev_vill_wzaqatala$value, # stroke.feature = your feature value
            stroke.color = c("black", "white"), 
            label = ev_vill_wzaqatala$lang,
            zoom.control = T,
            popup = paste("<b>Village:</b>", ev_vill_wzaqatala$village, "<br>", 
                          "<b>Source:</b>", ev_vill_wzaqatala$source, ev_vill_wzaqatala$page, "<br>",
                          "<b>Datapoint:</b>", ev_vill_wzaqatala$datapoint, "-", ev_vill_wzaqatala$idiom.x),
            width = 3, stroke.radius = 8,
            legend = FALSE)


```

### Map: General datapoints and refinement

```{r, echo=FALSE, warning=FALSE, message=FALSE, fig.width = 9.5}


# This is just for illustrative purposes. If we end up deciding on this visualization, obviously we need a more elegant solution :)

map.feature(lang.gltc(core_data$glottocode),
            latitude = core_data$gltc_lat,
            longitude = core_data$gltc_lon,
            features = core_data$lang, # color feature = language
            color = core_data$lang_color_dagatlas,
            stroke.features = core_data$value, # stroke.feature = your feature value
            stroke.color = c("black", "white"), 
            label = core_data$lang,
            zoom.control = T,
            popup = paste("<b>Source:</b>", core_data$source, core_data$page, "<br>",
                          "<b>Datapoint:</b>", core_data$datapoint),
            width = 3, stroke.radius = 8,
            legend = FALSE) %>%
  map.feature(lang.gltc(zaqatala$glottocode),
              latitude = zaqatala$lat,
              longitude = zaqatala$lon,
              features = zaqatala$lang, # color feature = language
              color = zaqatala$lang_color_dagatlas,
              stroke.features = zaqatala$value, # stroke.feature = your feature value
              stroke.color = c("black"), 
              stroke.legend = FALSE,
              label = zaqatala$lang,
              zoom.control = T,
              popup = paste("<b>Village:</b>", zaqatala$village, "<br>", 
                            "<b>Source:</b>", zaqatala$source, zaqatala$page, "<br>",
                            "<b>Datapoint:</b>", zaqatala$datapoint),
              width = 3, stroke.radius = 8,
              legend = FALSE,
              pipe.data = .)

```

## Datatable

```{r}

# select which feature data you want to show in the datatable

dtable <- ev %>%
  select(-c(type, core, exception))

cit <- vector("character", length(dtable$source))  
for (i in seq_along(dtable$source)) 
  {
  if (grepl("; ", dtable$source[[i]], fixed = TRUE) == TRUE) 
    {
  cits = strsplit(dtable$source[[i]], "; ")
    for (j in seq_along(cits))
      { 
        cits[[j]] <- RefManageR::Cite(bib = bib, cits[[j]], .opt = list(max.names = 2))
      }
  dtable$source[[i]] = paste(cits, sep = "; ")
    } 
  else 
    {
      dtable$source[[i]] <- RefManageR::Cite(bib = bib, dtable$source[[i]], .opt = list(max.names = 2))
    }
}

# generate searchable datatable

DT::datatable(dtable, escape = FALSE, rownames = FALSE,
              options = list(pageLength = 15, dom = 'ftip'))
```

### References

```{r results = "asis", echo = FALSE}
PrintBibliography(bib, .opts = list(check.entries = FALSE, sorting = "nyt"))
```